version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: dev_db
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev-network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  golang-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Jakarta
    depends_on:
      - db
    env_file:
      - env/backend.env.production
    networks:
      - dev-network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 3s
      retries: 3
    # Jika backend perlu ekspos port untuk debug, uncomment:
    # ports:
    #   - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        ENV_FILE: ./env/frontend.env.production
    restart: always
    depends_on:
      - golang-backend
    env_file:
      - env/frontend.env.production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "127.0.0.1:3131:80"
    networks:
      - dev-network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  pgdata:
  minio_data:
  keycloak_db_data:

networks:
  dev-network:
    driver: bridge
