version: '3.8'

services:
  db:
    image: postgres:15
    # container_name: production-postgres
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: dev_db
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev-network

  golang-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # container_name: ujian-backend-production
    restart: always
    depends_on:
      - db
    env_file:
      - env/backend.env.production
    networks:
      - dev-network
    
    healthcheck:
      test: curl -f http://localhost:8080 || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
    # ❌ Tidak diekspos ke luar

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        ENV_FILE: ./env/frontend.env.production
    # container_name: ujian-frontend-production
    restart: always
    depends_on:
      - golang-backend
    env_file:
      - env/frontend.env.production
    healthcheck:
      test: curl -f http://localhost || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
    # ❌ Tidak diekspos ke luar
    ports:
    - "127.0.0.1:3131:80"
    networks:
      - dev-network

volumes:
  pgdata:
  minio_data:
  keycloak_db_data:

networks:
  dev-network:
    driver: bridge
