version: '3.8'

services:
  db:
    image: postgres:15
    container_name: dev-postgres
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev-network

  redis:
    image: redis:alpine
    container_name: dev-redis
    ports:
      - "6379:6379"
    networks:
      - dev-network

  mailhog:
    image: mailhog/mailhog
    container_name: dev-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"  # SMTP
    networks:
      - dev-network

  minio:
    image: minio/minio
    container_name: dev-minio
    restart: always
    ports:
      - "9000:9000"    # S3 API
      - "9001:9001"    # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - dev-network

  keycloak-db:
    image: postgres:15
    container_name: dev-keycloak-db
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpass
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - dev-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: dev-keycloak
    command: start-dev
    depends_on:
      - keycloak-db
    ports:
      - "9090:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpass
      KC_DB_DATABASE: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
    networks:
      - dev-network

volumes:
  pgdata:
  minio_data:
  keycloak_db_data:

networks:
  dev-network:
    driver: bridge
